- name: install unzip and wget
  apt:
    name:
      - unzip
      - wget

- name: download the zip file
  get_url:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.3.zip
    dest: /opt/
    mode: 0755

- name: Create /opt/sonarqube/
  file:
    path: /opt/sonarqube/
    state: directory
    mode: '0755'

- name: Extract the zip file
  unarchive:
    src: /opt/sonarqube-7.9.3.zip
    dest: /opt/
    remote_src: yes

- name: Copy /opt/sonarqube/
  copy:
    src: /opt/sonarqube-7.9.3/
    dest: /opt/sonarqube/
    remote_src: yes
    follow: yes

- name: remove the zip file
  file:
    path: /opt/sonarqube-7.9.3.zip
    state: absent

- name: add user to run sonar
  shell: useradd -c "user to run SonarQube" -d /opt/sonarqube -g sonar sonar 

- name: change ownership
  shell: chown sonar:sonar /opt/sonarqube -R
    
- name: Configuring the SonarQube Server
  template:
    src: templates/sonar.properties.j2
    dest: /opt/sonarqube/conf/sonar.properties
    force: yes

- name: Update user in sonar.sh filee
  lineinfile:
    path: /opt/sonarqube/bin/linux-x86-64/sonar.sh
    regexp: '^#RUN_AS_USER='
    state: present
    line: RUN_AS_USER=sonar
    

- name: create a service file
  template:
    src: templates/sonarqube.service.j2
    dest:  /etc/systemd/system/sonar.service
    force: yes
